version: '3.8'

services:
  app:
    build: .
    ports:
      - "5173:5173"
    environment:
      - PORT=5173
      - NODE_ENV=production
    volumes:
      - ./db_shared.json:/app/db_shared.json
      - ./firebase-key.json:/app/firebase-key.json
    restart: always
